#!/usr/bin/env python3

"""Program"""
def main():
    """prog"""
    num1 = int(input("What is the 1st number?"))
    num2 = int(input("What is the 2nd number?"))
    print(str(num1) + " + " + str(num2) + " = " + str(num1+num2))
    print(str(num1) + " - " + str(num2) + " = " + str(num1-num2))
    print(str(num1) + " x " + str(num2) + " = " + str(num1*num2))
    print(str(num1) + " / " + str(num2) + " = " + str(num1/num2))

if __name__ == '__main__':
    main()
