#!/usr/bin/env python3

"""Year Calculator"""
from datetime import datetime

def main():
    """Calculate retirement year"""
    today = datetime.today()
    #print(today.year)
    age = int(input("What is your current age? "))
    retire_age = int(input("At what age would you like to retire? "))
    retire_year = today.year + retire_age - age
    print("You have " + str(retire_age-age) + " years left until you can retire." + "\nIt's " + str(today.year) + ", so you can retire in " + str(retire_year) + ".")

if __name__ == '__main__':
    main()
